name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # ğŸ”¹ RÃ©cupÃ©rer le code du repository
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "ğŸ’¡ The repository has been cloned to the runner."

      # ğŸ”¹ Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # ğŸ”¹ Installer pytest
      - name: Install pytest
        run: pip install pytest

      # ğŸ”¹ Lancer les tests unitaires
      - name: Run unit tests
        run: pytest

      - run: echo "ğŸ This job's status is ${{ job.status }}."
